_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "./pretrained_model/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024_dsconv.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
SOLVER:
  MAX_ITER: 90000
  BASE_LR: 2.5e-4
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (512, 1024)
OUTPUT_DIR: './logs/cs_R52_dsconv_bs2'

